name: "Swaps order keeper deploy"
description: "Pushes order keeper image to gcp"

env:

inputs:
    dry-run: # id of input
        description: "Dry run deploymenets will go through each stage besides pushing the configuration to production"
        default: true
    gcp-sa-key:
        description: "A google cloud service account key"
        required: true
    project-id:
        description: "The google cloud project id"
        required: true

runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: vmware-tanzu/carvel-setup-action@v1

        # Alternative option - authentication via credentials json
        - id: "auth"
          uses: "google-github-actions/auth@v0"
          with:
              credentials_json: "${{ inputs.gcp-sa-key }}"

        # Setup gcloud CLI
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v0

        # Configure Docker to use the gcloud command-line tool as a credential
        # helper for authentication
        - run: |-
              gcloud --quiet auth configure-docker
          shell: bash

        - name: Cache install packages
          uses: ./.github/actions/cache-install

        - name: Build apps
          run: |
              yarn build
          shell: bash

        # Build the Docker image
        - name: Build docker image
          run: |-
              docker build \
                -f "./packages/swaps-order-keeper/Dockerfile" \
                --tag "gcr.io/${{ inputs.project-id }}/swaps-order-keeper:$GITHUB_SHA" \
                --tag "latest" \
                --build-arg GITHUB_SHA="$GITHUB_SHA" \
                --build-arg GITHUB_REF="$GITHUB_REF" \
                .
          shell: bash

        # Push the Docker image to Google Container Registry
        - name: Publish docker image
          if: ${{ inputs.dry-run }} == false
          run: |-
              docker push "gcr.io/${{ inputs.project-id }}/swaps-order-keeper:$GITHUB_SHA"
          shell: bash
