name: Deploy image to cloud registry

on:
    push:
        branches: [master]
        paths: ["packages/swaps-order-keeper/**"]

env:
    PROJECT_ID: ${{ secrets.GKE_PROJECT }}
    IMAGE: swaps-order-keeper

jobs:
    setup-and-deploy:
        name: Setup and Deploy
        runs-on: ubuntu-latest

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: vmware-tanzu/carvel-setup-action@v1

            # Configure Workload Identity Federation and generate an access token.
            #- id: 'auth'
            # name: 'Authenticate to Google Cloud'
            # uses: 'google-github-actions/auth@v0'
            # with:
            # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

            # Alternative option - authentication via credentials json
            - id: "auth"
              uses: "google-github-actions/auth@v0"
              with:
                  credentials_json: "${{ secrets.GKE_SA_KEY }}"

            # Setup gcloud CLI
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker

            - run: yarn install --frozen-lockfile
            - run: npm run build

            # Build the Docker image
            - name: Build
              run: |-
                  docker build \
                    --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
                    --tag "latest" \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    .

            # Push the Docker image to Google Container Registry
            - name: Publish
              run: |-
                  docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
